# .streamlit/secrets.toml
SUPABASE_URL = "https://juembbxegctdkktdwhdl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZW1iYnhlZ2N0ZGtrdGR3aGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjQxNzYsImV4cCI6MjA2NzA0MDE3Nn0.XVUZ4kYq1YHmclfsQ1W8dtWMHadyyqGHPEg1L-p-QKs"